# Generated by Django 3.1.2 on 2020-10-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='Category',
            new_name='category',
        ),
    ]
