# Generated by Django 3.1.2 on 2020-10-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20201014_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='_images',
            new_name='i_images',
        ),
    ]
