# Generated by Django 3.1.2 on 2020-10-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20201014_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
